{% set name = 'sdv' %}
{% set version = '0.12.1.dev0' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - pytest-runner
    - graphviz
    - python >=3.6,<3.9
    - faker >=1.0.1,<4.15.0
    - python-graphviz >=0.13.2,<1
    - numpy >=1.18.0,<2
    - pandas >=1.1,<1.1.5
    - pytorch >=1.4,<2
    - tqdm >=4.14,<5
    - copulas >=0.5.0,<0.6
    - ctgan >=0.4.3,<0.5
    - deepecho >=0.2.0,<0.3
    - rdt >=0.5.0,<0.6
    - sdmetrics >=0.3.1,<0.4
    - torchvision >=0.5.0,<1
    - sktime >=0.4,<0.6
    - pomegranate >=0.13.4,<0.14.2
  run:
    - graphviz
    - python >=3.6,<3.9
    - faker >=1.0.1,<4.15.0
    - python-graphviz >=0.13.2,<1
    - numpy >=1.18.0,<2
    - pandas >=1.1,<1.1.5
    - pytorch >=1.4,<2
    - tqdm >=4.14,<5
    - copulas >=0.5.0,<0.6
    - ctgan >=0.4.3,<0.5
    - deepecho >=0.2.0,<0.3
    - rdt >=0.5.0,<0.6
    - sdmetrics >=0.3.1,<0.4
    - torchvision >=0.5.0,<1
    - sktime >=0.4,<0.6
    - pomegranate >=0.13.4,<0.14.2

about:
  home: "https://sdv.dev"
  license: MIT
  license_family: MIT
  license_file: "LICENSE"
  summary: "Synthetic Data Generation for tabular, relational and time series data."
  doc_url: "https://sdv.dev/SDV"
  dev_url: "https://github.com/sdv-dev/SDV"

extra:
  recipe-maintainers:
    - sdv-dev
